#!/usr/bin/env bash
# 
# Siddharth Dushantha 2025
#
# Wrapper around 'ss -tunlp' for a cleaner output.
#

version="1.0.0"

usage(){
    echo "USAGE: oports [OPTION] | [FILTER]

OPTIONS
-h, --help
        Show help
--version
        Show version

AVAILABLE FILTERS
  port    Filter by port number
  proc    Filter by proccess name
  pid     Filter by process ID
  ip      Filter by IP 
  user    Filter by owning user

FILTER SYNTAX
  <key>:<value>

EXAMPLE USAGES
  oports
  oports proc:nc
  oports ip:0.0.0.0

If the process belongs to another user, the process name and PID will be set
to '*' and the username will be set to '?'. Run using 'sudo' to view the values."
}

list_open_ports() {
    filter="$1"
    filter_key="${filter%:*}"
    filter_value="${filter#*:}"

    # An associative array is needed so that we can keep track of which filter
    # goes to which column. We're starting from 1 intead of 0 as 'awk' doesnt
    # have array like index.
    declare -A valid_filters=([port]=1 [proc]=2 [pid]=3 [ip]=4 [user]=5)

    # Extra padding is needed so that the underlines under the column heading
    # "User" matches the length for the longest line. 'useradd' has a maximum
    # username length of 32 characters. So by adding 32 extra whitespaces, we
    # will ensure that the underline will never be too short. It will also
    # never be too long since 'column' splits the input based on whitespace
    # and will therefore ignore any trailing whitespaces.
    extra_padding=$(printf "%*s" 32 "")

    output=$(ss -tulnp | awk '/LISTEN/ {
        process = "*"
        if (match($0, /"([^"]+)"/)) {
            process = substr($0, RSTART + 1, RLENGTH - 2)
        }

        pid = "*"
        if (match($0, /pid=([0-9]+)/)) {
            pid = substr($0, RSTART + 4, RLENGTH - 4)
        }

        split($5, _port, ":")
        port = _port[length(_port)]

        if (match($5, /^(.*):/)) {
            ip = substr($5, RSTART, RLENGTH - 1)
        }

        if (process == "*") {
            user = " ?"
        } else {
            cmd = "ps -o user= -p " pid
            cmd | getline user
            close(cmd)
        }

        print port, process, pid, ip, user
    }' | sort -n)


    if [[ -n "$filter" ]] && [[ -z "${valid_filters[$filter_key]}" ]]; then
        echo "Invalid filter: $filter_key"
        exit 1
    fi

    if [[ -n "$filter" ]]; then
        output=$(awk "\$${valid_filters[$filter_key]} ~ /$filter_value/" <<< "$output")
    fi

    [[ -z "$output" ]] && exit

    {
        echo -e "\e[1;37;4mPort Process PID IP User$extra_padding\e[0m"
        echo "$output"
    } | column -t -o "  "
} 

main(){
    while [ "$1" ]; do
        case "$1" in
            --help | -h) usage && exit ;;
            --version) echo "$version" && exit ;;
            *:*) list_open_ports "$1" && exit ;;
            -*) echo "Option '$1' does not exist" && exit 1;;
        esac
        shift
    done

    list_open_ports
}

main "$@"
